package model

import "time"

// AlertNotification records health alerts generated by the monitoring system.
// Alerts are per-user-group (target_type="group") or per-model (target_type="model").
// user_id=0 means the alert is global (not yet attributed to individual users).
type AlertNotification struct {
	ID             int64  `gorm:"primaryKey" json:"id"`
	UserID         int    `gorm:"index:idx_alert_user_created,priority:1;default:0" json:"user_id"`
	TargetType     string `gorm:"type:varchar(32)" json:"target_type"` // "group" | "model"
	TargetName     string `gorm:"type:varchar(255)" json:"target_name"`
	AlertType      string `gorm:"type:varchar(64);index" json:"alert_type"`           // group_unhealthy | model_unavailable | ...
	Severity       string `gorm:"type:varchar(16);default:'warning'" json:"severity"` // info | warning | critical
	Title          string `gorm:"type:varchar(255)" json:"title"`
	Message        string `gorm:"type:text" json:"message"`
	Recommendation string `gorm:"type:text" json:"recommendation"`                       // JSON array of recommendations
	Status         string `gorm:"type:varchar(32);default:'unread';index" json:"status"` // unread | read | dismissed
	ActionTaken    string `gorm:"type:varchar(255)" json:"action_taken"`
	CreatedAt      int64  `gorm:"index:idx_alert_user_created,priority:2" json:"created_at"`
	ReadAt         int64  `json:"read_at"`
}

func (a *AlertNotification) TableName() string { return "alert_notifications" }

// HasRecentAlert checks whether a similar alert was already raised within the last
// windowSeconds seconds, to prevent alert storms.
func HasRecentAlert(targetName, alertType string, windowSeconds int64) (bool, error) {
	var count int64
	cutoff := nowUnix() - windowSeconds
	err := DB.Model(&AlertNotification{}).
		Where("target_name = ? AND alert_type = ? AND created_at > ?", targetName, alertType, cutoff).
		Count(&count).Error
	return count > 0, err
}

// GetUserAlerts returns alerts for a user with optional status filter.
func GetUserAlerts(userID int, status string, limit int) ([]AlertNotification, error) {
	var alerts []AlertNotification
	q := DB.Where("user_id IN ?", []int{0, userID})
	if status != "" && status != "all" {
		q = q.Where("status = ?", status)
	}
	err := q.Order("created_at desc").Limit(limit).Find(&alerts).Error
	return alerts, err
}

// CountUnreadAlerts returns the number of unread alerts for a user.
func CountUnreadAlerts(userID int) (int64, error) {
	var count int64
	err := DB.Model(&AlertNotification{}).
		Where("user_id IN ? AND status = ?", []int{0, userID}, "unread").
		Count(&count).Error
	return count, err
}

// MarkAlertRead marks an alert as read and records the optional action taken.
func MarkAlertRead(alertID int64, userID int, action string) error {
	updates := map[string]interface{}{
		"status":  "read",
		"read_at": nowUnix(),
	}
	if action != "" {
		updates["action_taken"] = action
	}
	return DB.Model(&AlertNotification{}).
		Where("id = ? AND user_id IN ?", alertID, []int{0, userID}).
		Updates(updates).Error
}

func nowUnix() int64 {
	return time.Now().Unix()
}
