package settingsaccess

func buildDefinitions() map[string]Definition {
	items := []Definition{
		scope(ScopeChannelProfitPreview, "GroupRatio"),
		configScope(ScopeVeridropDetection, "veridrop_monitor_setting",
			[]string{
				"veridrop_monitor_setting.enabled",
				"veridrop_monitor_setting.base_url",
				"veridrop_monitor_setting.admin_api_key",
				"veridrop_monitor_setting.default_mode",
				"veridrop_monitor_setting.default_openai_wire_api",
				"veridrop_monitor_setting.include_long_context",
				"veridrop_monitor_setting.include_long_context_extreme",
				"veridrop_monitor_setting.max_concurrent",
				"veridrop_monitor_setting.batch_size",
				"veridrop_monitor_setting.submit_timeout_seconds",
				"veridrop_monitor_setting.poll_interval_seconds",
				"veridrop_monitor_setting.job_timeout_seconds",
				"veridrop_monitor_setting.auto_detection_enabled",
				"veridrop_monitor_setting.detection_interval_minutes",
			},
			[]string{
				"enabled", "base_url", "admin_api_key", "default_mode", "default_openai_wire_api",
				"include_long_context", "include_long_context_extreme", "max_concurrent", "batch_size",
				"submit_timeout_seconds", "poll_interval_seconds", "job_timeout_seconds",
				"auto_detection_enabled", "detection_interval_minutes",
			}),
		scope("site.system-info", "theme.frontend", "SystemName", "Logo", "Footer", "About", "HomePageContent", "ServerAddress", "legal.user_agreement", "legal.privacy_policy"),
		scope("site.notice", "Notice"),
		scope("site.header-navigation", "HeaderNavModules"),
		scope("site.sidebar-modules", "SidebarModulesAdmin"),
		scope("auth.basic-auth", "PasswordLoginEnabled", "PasswordRegisterEnabled", "EmailVerificationEnabled", "RegisterEnabled", "EmailDomainRestrictionEnabled", "EmailAliasRestrictionEnabled", "EmailDomainWhitelist"),
		scope("auth.oauth", "ServerAddress", "GitHubOAuthEnabled", "GitHubClientId", "GitHubClientSecret", "discord.enabled", "discord.client_id", "discord.client_secret", "oidc.enabled", "oidc.display_name", "oidc.client_id", "oidc.client_secret", "oidc.well_known", "oidc.authorization_endpoint", "oidc.token_endpoint", "oidc.user_info_endpoint", "TelegramOAuthEnabled", "TelegramBotToken", "TelegramBotName", "LinuxDOOAuthEnabled", "LinuxDOClientId", "LinuxDOClientSecret", "LinuxDOMinimumTrustLevel", "WeChatAuthEnabled", "WeChatServerAddress", "WeChatServerToken", "WeChatAccountQRCodeImageURL"),
		scope("auth.passkey", "passkey.enabled", "passkey.rp_display_name", "passkey.rp_id", "passkey.origins", "passkey.allow_insecure_origin", "passkey.user_verification", "passkey.attachment_preference"),
		scope("auth.bot-protection", "TurnstileCheckEnabled", "TurnstileSiteKey", "TurnstileSecretKey"),
		scope("auth.custom-oauth", "ServerAddress"),
		scope("billing.quota", "QuotaForNewUser", "PreConsumedQuota", "QuotaForInviter", "QuotaForInvitee", "TopUpLink", "general_setting.docs_link", "quota_setting.enable_free_model_pre_consume", "payment_setting.compliance_confirmed", "payment_setting.compliance_terms_version"),
		scope("billing.currency", "QuotaPerUnit", "USDExchangeRate", "DisplayInCurrencyEnabled", "DisplayTokenStatEnabled", "general_setting.quota_display_type", "general_setting.custom_currency_symbol", "general_setting.custom_currency_exchange_rate"),
		scope("billing.model-pricing", "ModelPrice", "ModelRatio", "CacheRatio", "CreateCacheRatio", "CompletionRatio", "ImageRatio", "AudioRatio", "AudioCompletionRatio", "ExposeRatioEnabled", "billing_setting.billing_mode", "billing_setting.billing_expr", "tool_price_setting.prices", "thirdpartysd2_pricing.matrix", "CompletionRatioMeta"),
		scope(ScopeBillingGroupPricing, "TopupGroupRatio", "GroupRatio", "UserUsableGroups", "GroupGroupRatio", "AutoGroups", "MaxTokenAutoGroups", "DefaultUseAutoGroup", "UserExclusiveGroupRatioEnabled", "UserExclusiveGroupRatioCacheMax", "group_ratio_setting.group_special_usable_group"),
		scope("billing.payment", "PayAddress", "EpayId", "EpayKey", "Price", "MinTopUp", "CustomCallbackAddress", "PayMethods", "payment_setting.amount_options", "payment_setting.amount_discount", "payment_setting.compliance_confirmed", "payment_setting.compliance_terms_version", "payment_setting.compliance_confirmed_at", "payment_setting.compliance_confirmed_by", "payment_setting.compliance_confirmed_ip", "StripeEnabled", "StripeApiSecret", "StripeWebhookSecret", "StripePriceId", "StripeUnitPrice", "StripeUseRealtimeRate", "StripeMinTopUp", "StripePromotionCodesEnabled", "CreemApiKey", "CreemWebhookSecret", "CreemTestMode", "CreemProducts", "WaffoEnabled", "WaffoApiKey", "WaffoPrivateKey", "WaffoPublicCert", "WaffoSandboxPublicCert", "WaffoSandboxApiKey", "WaffoSandboxPrivateKey", "WaffoSandbox", "WaffoMerchantId", "WaffoCurrency", "WaffoUnitPrice", "WaffoMinTopUp", "WaffoNotifyUrl", "WaffoReturnUrl", "WaffoPayMethods", "WaffoPancakeMerchantID", "WaffoPancakePrivateKey", "WaffoPancakeReturnURL", "WaffoPancakeStoreID", "WaffoPancakeProductID", "AlipayEnabled", "AlipayAppId", "AlipayPrivateKey", "AlipayPublicKey", "AlipaySandbox", "AlipayMinTopUp", "AlipayNotifyUrl", "AlipayReturnUrl", "WechatEnabled", "WechatAppId", "WechatMchId", "WechatApiV3Key", "WechatMchPrivateKey", "WechatMchCertSerialNo", "WechatMinTopUp", "WechatNotifyUrl", "InfiniEnabled", "InfiniApiKey", "InfiniApiSecret", "InfiniWebhookSecret", "InfiniSandbox", "InfiniNotifyUrl", "InfiniReturnUrl", "InfiniFailUrl", "InfiniUnitPrice", "InfiniMinTopUp", "InfiniCurrency", "InfiniCurrencies", "InfiniPayMethods"),
		scope("billing.checkin", "checkin_setting.enabled", "checkin_setting.min_quota", "checkin_setting.max_quota"),
		scope("models.global", "global.pass_through_request_enabled", "global.thinking_model_blacklist", "global.chat_completions_to_responses_policy", "general_setting.ping_interval_enabled", "general_setting.ping_interval_seconds"),
		scope("models.routing-reliability", "RetryTimes", "ChannelDisableThreshold", "AutomaticDisableChannelEnabled", "AutomaticEnableChannelEnabled", "AutomaticDisableKeywords", "AutomaticDisableStatusCodes", "AutomaticRetryStatusCodes", "monitor_setting.auto_test_channel_enabled", "monitor_setting.auto_test_channel_minutes", "monitor_setting.channel_test_mode"),
		scope("models.gemini", "gemini.safety_settings", "gemini.version_settings", "gemini.supported_imagine_models", "gemini.thinking_adapter_enabled", "gemini.thinking_adapter_budget_tokens_percentage", "gemini.function_call_thought_signature_enabled", "gemini.remove_function_response_id_enabled"),
		scope("models.claude", "claude.model_headers_settings", "claude.default_max_tokens", "claude.thinking_adapter_enabled", "claude.thinking_adapter_budget_tokens_percentage"),
		scope("models.grok", "grok.violation_deduction_enabled", "grok.violation_deduction_amount"),
		scope("models.channel-affinity", "channel_affinity_setting.enabled", "channel_affinity_setting.switch_on_success", "channel_affinity_setting.keep_on_channel_disabled", "channel_affinity_setting.max_entries", "channel_affinity_setting.default_ttl_seconds", "channel_affinity_setting.rules"),
		scope("models.model-deployment", "model_deployment.ionet.enabled", "model_deployment.ionet.api_key"),
		scope("security.rate-limit", "ModelRequestRateLimitEnabled", "ModelRequestRateLimitCount", "ModelRequestRateLimitSuccessCount", "ModelRequestRateLimitDurationMinutes", "ModelRequestRateLimitGroup"),
		scope("security.sensitive-words", "CheckSensitiveEnabled", "CheckSensitiveOnPromptEnabled", "SensitiveWords"),
		scope("security.ssrf", "fetch_setting.enable_ssrf_protection", "fetch_setting.allow_private_ip", "fetch_setting.domain_filter_mode", "fetch_setting.ip_filter_mode", "fetch_setting.domain_list", "fetch_setting.ip_list", "fetch_setting.allowed_ports", "fetch_setting.apply_ip_filter_for_domain"),
		scope("security.token-limits", "token_setting.max_user_tokens"),
		scope("content.dashboard", "DataExportEnabled", "DataExportInterval", "DataExportDefaultTime"),
		scope("content.announcements", "console_setting.announcements_enabled", "console_setting.announcements", "Announcements"),
		scope("content.api-info", "console_setting.api_info_enabled", "console_setting.api_info", "ApiInfo"),
		scope("content.faq", "console_setting.faq_enabled", "console_setting.faq", "FAQ"),
		scope("content.uptime-kuma", "console_setting.uptime_kuma_enabled", "console_setting.uptime_kuma_groups", "UptimeKumaUrl", "UptimeKumaSlug"),
		scope("content.chat", "Chats"),
		scope("content.drawing", "DrawingEnabled", "MjNotifyEnabled", "MjAccountFilterEnabled", "MjForwardUrlEnabled", "MjModeClearEnabled", "MjActionCheckSuccessEnabled"),
		scope("operations.node-control", "NodeControlServiceUrl"),
		scope("operations.behavior", "DefaultCollapseSidebar", "DemoSiteEnabled", "SelfUseModeEnabled"),
		scope("operations.alerts", "QuotaRemindThreshold", "perf_metrics_setting.enabled", "perf_metrics_setting.flush_interval", "perf_metrics_setting.bucket_time", "perf_metrics_setting.retention_days"),
		scope("operations.email", "SMTPServer", "SMTPPort", "SMTPAccount", "SMTPFrom", "SMTPToken", "SMTPSSLEnabled", "SMTPStartTLSEnabled", "SMTPInsecureSkipVerify", "SMTPForceAuthLogin"),
		scope("operations.worker", "WorkerUrl", "WorkerValidKey", "WorkerAllowHttpImageRequestEnabled"),
		scope("operations.logs", "LogConsumeEnabled"),
		scope("operations.request-log", "RequestLogEnabled", "RequestLogUsername", "RequestLogMaxBodyKB", "RequestLogMinCount", "RequestLogMaxCount"),
		scope("operations.performance", "performance_setting.disk_cache_enabled", "performance_setting.disk_cache_threshold_mb", "performance_setting.disk_cache_max_size_mb", "performance_setting.disk_cache_path", "performance_setting.monitor_enabled", "performance_setting.monitor_cpu_threshold", "performance_setting.monitor_memory_threshold", "performance_setting.monitor_disk_threshold"),
		scope("operations.update-checker"),
		configScope("system-tuning.gateway-rate-limit", "rate_limit_setting",
			[]string{"rate_limit_setting.global_api_enabled", "rate_limit_setting.global_api_num", "rate_limit_setting.global_api_duration_sec", "rate_limit_setting.global_api_user_enabled", "rate_limit_setting.global_api_user_num", "rate_limit_setting.global_api_user_duration_sec", "rate_limit_setting.global_web_enabled", "rate_limit_setting.global_web_num", "rate_limit_setting.global_web_duration_sec", "rate_limit_setting.critical_enabled", "rate_limit_setting.critical_num", "rate_limit_setting.critical_duration_sec", "rate_limit_setting.auth_refresh_enabled", "rate_limit_setting.auth_refresh_num", "rate_limit_setting.auth_refresh_ip_num", "rate_limit_setting.auth_refresh_duration_sec", "rate_limit_setting.search_enabled", "rate_limit_setting.search_num", "rate_limit_setting.search_duration_sec", "rate_limit_setting.log_export_enabled", "rate_limit_setting.log_export_num", "rate_limit_setting.log_export_duration_sec", "rate_limit_setting.redis_timeout_ms"},
			[]string{"global_api_enabled", "global_api_num", "global_api_duration_sec", "global_api_user_enabled", "global_api_user_num", "global_api_user_duration_sec", "global_web_enabled", "global_web_num", "global_web_duration_sec", "critical_enabled", "critical_num", "critical_duration_sec", "auth_refresh_enabled", "auth_refresh_num", "auth_refresh_ip_num", "auth_refresh_duration_sec", "search_enabled", "search_num", "search_duration_sec", "log_export_enabled", "log_export_num", "log_export_duration_sec", "redis_timeout_ms"}),
		configScope("system-tuning.relay-timeout", "relay_timeout_setting",
			[]string{"relay_timeout_setting.enabled", "relay_timeout_setting.response_timeout_seconds", "relay_timeout_setting.total_timeout_seconds"},
			[]string{"enabled", "response_timeout_seconds", "total_timeout_seconds"}),
		configScope("system-tuning.database-pool", "db_pool_setting",
			[]string{"db_pool_setting.max_idle_conns", "db_pool_setting.max_open_conns", "db_pool_setting.max_lifetime_sec", "db_pool_setting.log_max_idle_conns", "db_pool_setting.log_max_open_conns"},
			[]string{"max_idle_conns", "max_open_conns", "max_lifetime_sec", "log_max_idle_conns", "log_max_open_conns"}),
		configScope("system-tuning.login-session-policy", "user_session_setting",
			[]string{"user_session_setting.active_limit", "user_session_setting.issuance_limit", "user_session_setting.issuance_window_sec", "user_session_setting.revoked_retention_days", "user_session_setting.hourly_alert_threshold"},
			[]string{"active_limit", "issuance_limit", "issuance_window_sec", "revoked_retention_days", "hourly_alert_threshold"}),
		scope("system-tuning.settlement-guard", "business_stats_circuit_breaker_setting.enabled", "business_stats_circuit_breaker_setting.manual_disabled", "business_stats_circuit_breaker_setting.failure_threshold", "business_stats_circuit_breaker_setting.initial_cooldown_seconds", "business_stats_circuit_breaker_setting.max_cooldown_seconds", "business_stats_circuit_breaker_setting.side_effect_db_timeout_ms"),
		scope("system-tuning.ledger-pipeline", "ledger_pipeline_setting.flush_interval_sec", "ledger_pipeline_setting.outer_batch_size", "ledger_pipeline_setting.cost_outer_batch_size", "ledger_pipeline_setting.inner_batch_size", "ledger_pipeline_setting.settlement_flush_max_per_cycle", "ledger_pipeline_setting.cost_flush_max_per_cycle", "ledger_pipeline_setting.full_drain", "ledger_pipeline_setting.buf_max_entries", "ledger_pipeline_setting.dedup_mem_max_entries", "ledger_pipeline_setting.dedup_use_redis", "ledger_pipeline_setting.dedup_redis_ttl_sec", "ledger_pipeline_setting.flush_db_timeout_sec", "ledger_pipeline_setting.fallback_queue_capacity", "ledger_pipeline_setting.shutdown_timeout_sec", "ledger_pipeline_setting.cache_ttl_secs", "ledger_pipeline_setting.cache_ttl_jitter_percent", "ledger_retry_setting.retry_flush_interval_sec", "ledger_retry_setting.stat_upsert_max_retries", "ledger_retry_setting.retry_queue_max_entries", "ledger_retry_setting.allow_concurrent_flush"),
		scope("system-tuning.relay-log-pipeline", "relay_log_pipeline_setting.enabled", "relay_log_pipeline_setting.consume_buf_max_entries", "relay_log_pipeline_setting.error_buf_max_entries", "relay_log_pipeline_setting.continuation_buf_max_entries", "relay_log_pipeline_setting.outer_batch_size", "relay_log_pipeline_setting.inner_batch_size", "relay_log_pipeline_setting.flush_max_per_cycle", "relay_log_pipeline_setting.full_drain", "relay_log_pipeline_setting.flush_interval_ms", "relay_log_pipeline_setting.write_timeout_sec", "relay_log_pipeline_setting.fallback_queue_capacity", "relay_log_pipeline_setting.fallback_max_file_size_mb", "relay_log_pipeline_setting.fallback_max_files", "relay_log_pipeline_setting.shutdown_timeout_sec", "relay_log_retry_setting.retry_flush_interval_ms", "relay_log_retry_setting.max_retries", "relay_log_retry_setting.retry_buf_max_entries", "relay_log_retry_setting.allow_concurrent_flush", "relay_log_retry_setting.circuit_failure_threshold", "relay_log_retry_setting.circuit_open_sec"),
		scope("system-tuning.export-settings", "payment_setting.user_export_max_rows", "export_setting.user_export_enabled", "export_setting.rate_limit_cooldown_sec", "export_setting.hard_ceiling_rows"),
		scope("system-tuning.log-query", "log_query_setting.stat_cache_enabled", "log_query_setting.stat_cache_ttl_hours", "log_query_setting.current_hour_ttl_sec", "log_query_setting.warm_enabled", "log_query_setting.warm_hours", "log_query_setting.query_timeout_ms"),
		scope("system-tuning.log-export", "log_export_setting.enabled", "log_export_setting.offpeak_only", "log_export_setting.user_cooldown_sec", "log_export_setting.max_concurrent_jobs", "log_export_setting.max_active_jobs_per_user", "log_export_setting.admin_max_range_sec", "log_export_setting.timeout_sec", "log_export_setting.job_ttl_hours", "log_export_setting.max_templates_per_user", "log_export_setting.batch_size", "log_export_setting.batch_sleep_ms", "log_export_setting.batch_query_timeout_sec", "log_export_setting.window_sec", "log_export_setting.max_rows_per_sec", "log_export_setting.cpu_soft_limit", "log_export_setting.cpu_hard_limit", "log_export_setting.cpu_check_interval_ms", "log_export_setting.gzip_level", "log_export_setting.rows_per_file", "log_export_setting.max_parts", "log_export_setting.xlsx_max_rows", "log_export_setting.min_free_disk_mb", "log_export_setting.download_token_ttl_sec", "log_export_setting.download_session_ttl_sec", "log_export_setting.max_concurrent_downloads_per_user", "log_export_setting.offpeak_window"),
		scope("system-tuning.ledger-detail", "ledger_detail_setting.export_user_cooldown_sec", "ledger_detail_setting.export_batch_size", "ledger_detail_setting.export_batch_sleep_ms", "ledger_detail_setting.export_rows_per_file", "ledger_detail_setting.export_max_range_sec", "ledger_detail_setting.export_timeout_sec", "ledger_detail_setting.list_max_range_sec", "ledger_detail_setting.list_default_range_sec", "ledger_detail_setting.list_default_limit", "ledger_detail_setting.list_max_limit", "ledger_detail_setting.list_scan_batch_size", "ledger_detail_setting.list_scan_rows_per_req"),
		scope("system-tuning.fallback-backfill", "business_stats_fallback_backfill_setting.enabled", "business_stats_fallback_backfill_setting.use_separate_fallback_dir", "business_stats_fallback_backfill_setting.status_cache_seconds", "business_stats_fallback_backfill_setting.max_read_line_bytes", "business_stats_fallback_backfill_setting.write_batch_size", "business_stats_fallback_backfill_setting.flush_interval_sec", "business_stats_fallback_backfill_setting.batch_sleep_ms"),
	}

	result := make(map[string]Definition, len(items))
	for _, item := range items {
		result[item.Scope] = item
	}
	return result
}
