import type { SystemTuningSettings } from '../types'

// Safe UI fallbacks for the runtime-parameter page. Server-side `setting/` remains the source of truth.
export const systemTuningFallbackSettings: SystemTuningSettings = {
  'business_stats_circuit_breaker_setting.enabled': true,
  'business_stats_circuit_breaker_setting.manual_disabled': false,
  'business_stats_circuit_breaker_setting.failure_threshold': 3,
  'business_stats_circuit_breaker_setting.initial_cooldown_seconds': 60,
  'business_stats_circuit_breaker_setting.max_cooldown_seconds': 3600,
  'business_stats_circuit_breaker_setting.side_effect_db_timeout_ms': 800,
  'ledger_pipeline_setting.flush_interval_sec': 8,
  'ledger_pipeline_setting.outer_batch_size': 2000,
  'ledger_pipeline_setting.cost_outer_batch_size': 0,
  'ledger_pipeline_setting.inner_batch_size': 500,
  'ledger_pipeline_setting.settlement_flush_max_per_cycle': 15000,
  'ledger_pipeline_setting.cost_flush_max_per_cycle': 0,
  'ledger_pipeline_setting.full_drain': false,
  'ledger_pipeline_setting.buf_max_entries': 100000,
  'ledger_pipeline_setting.dedup_mem_max_entries': 200000,
  'ledger_pipeline_setting.dedup_use_redis': false,
  'ledger_pipeline_setting.dedup_redis_ttl_sec': 21600,
  'ledger_pipeline_setting.flush_db_timeout_sec': 30,
  'ledger_retry_setting.retry_flush_interval_sec': 2,
  'ledger_retry_setting.stat_upsert_max_retries': 10,
  'ledger_retry_setting.retry_queue_max_entries': 50000,
  'ledger_retry_setting.allow_concurrent_flush': false,
  'ledger_pipeline_setting.fallback_queue_capacity': 10000,
  'ledger_pipeline_setting.shutdown_timeout_sec': 25,
  'ledger_pipeline_setting.cache_ttl_secs': [300, 300, 300, 300, 300],
  'ledger_pipeline_setting.cache_ttl_jitter_percent': 20,
  'payment_setting.user_export_max_rows': 10000,
  'export_setting.user_export_enabled': true,
  'export_setting.rate_limit_cooldown_sec': 600,
  'export_setting.hard_ceiling_rows': 1000000,
  'ledger_detail_setting.export_user_cooldown_sec': 300,
  'ledger_detail_setting.export_batch_size': 3000,
  'ledger_detail_setting.export_batch_sleep_ms': 100,
  'ledger_detail_setting.export_rows_per_file': 1000000,
  'ledger_detail_setting.export_max_range_sec': 86400,
  'ledger_detail_setting.export_timeout_sec': 7200,
  'ledger_detail_setting.list_max_range_sec': 86400,
  'ledger_detail_setting.list_default_range_sec': 86400,
  'ledger_detail_setting.list_default_limit': 100,
  'ledger_detail_setting.list_max_limit': 200,
  'ledger_detail_setting.list_scan_batch_size': 2000,
  'ledger_detail_setting.list_scan_rows_per_req': 20000,
  'business_stats_fallback_backfill_setting.enabled': true,
  'business_stats_fallback_backfill_setting.use_separate_fallback_dir': false,
  'business_stats_fallback_backfill_setting.status_cache_seconds': 15,
  'business_stats_fallback_backfill_setting.max_read_line_bytes': 1048576,
  'business_stats_fallback_backfill_setting.write_batch_size': 200,
  'business_stats_fallback_backfill_setting.flush_interval_sec': 5,
  'business_stats_fallback_backfill_setting.batch_sleep_ms': 200,
}
