export const dashboardContentDefaults = {
  'console_setting.api_info': '',
  'console_setting.announcements': '',
  'console_setting.faq': '',
  'console_setting.uptime_kuma_groups': '',
  'console_setting.api_info_enabled': '',
  'console_setting.announcements_enabled': '',
  'console_setting.faq_enabled': '',
  'console_setting.uptime_kuma_enabled': '',
  ApiInfo: '',
  Announcements: '',
  FAQ: '',
  UptimeKumaUrl: '',
  UptimeKumaSlug: '',
  DataExportEnabled: false,
  DataExportDefaultTime: 'hour',
  DataExportInterval: 5,
};
